/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: CCU4 Timer Example
*              for ModusToolbox.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/
#include "cybsp.h"
#include "cy_utils.h"

/*******************************************************************************
* Macros
*******************************************************************************/
/* Defines priority level of the period match event interrupt */
#define TIMER_0_PERIOD_MATCH_EVENT_PRIORITY 63

/* Defines handler of the period match event interrupt */
#define TIMER_0_PERIOD_MATCH_EVENT_HANDLER CCU40_0_IRQHandler

/* Defines IRQ number of the period match event interrupt */
#define TIMER_0_PERIOD_MATCH_EVENT_IRQN CCU40_0_IRQn

/*******************************************************************************
* Global Variables
*******************************************************************************/
static volatile bool timer_interrupt_flag = false;

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. It sets up a CCU4 timer to period match interrupt. 
* The main while loop checks for the elapsed time due to CCU4 timer period match   
* event and toggles an LED at approximately 1Hz. 
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/

int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Set priority for CCU4 timer period match interrupt */
    NVIC_SetPriority(TIMER_0_PERIOD_MATCH_EVENT_IRQN, NVIC_EncodePriority(NVIC_GetPriorityGrouping(), TIMER_0_PERIOD_MATCH_EVENT_PRIORITY, 0));

    /* Enable CCU4 timer period match interrupt */
    NVIC_EnableIRQ(TIMER_0_PERIOD_MATCH_EVENT_IRQN);

    /* Start the CCU4 timer */
    XMC_CCU4_SLICE_StartTimer(TIMER_0_HW);

    while (1)
    {
        /* Check if timer elapsed (interrupt fired) and toggle the LED */
        if (timer_interrupt_flag)
        {
            /* Clear the flag */
            timer_interrupt_flag = false;

            /* Toggle the output port of GPIO */
            XMC_GPIO_ToggleOutput(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
        }
    }
}

/*******************************************************************************
* Function Name: TIMER_0_PERIOD_MATCH_EVENT_HANDLER
********************************************************************************
* Summary:
* This is the interrupt handler function for the CCU4 timer period match interrupt.
*
* Parameters:
*  none
*
* Return:
*  void
*
*******************************************************************************/
void TIMER_0_PERIOD_MATCH_EVENT_HANDLER(void)
{
    /* Set the flag */
    timer_interrupt_flag = true;   
}

/* [] END OF FILE */
